[package]
name = "execsnoop"
description = "Watch process executions in the Linux kernel with the process events connector"
repository = "https://github.com/pop-os/system76-scheduler"
version = "0.3.0"
edition = "2021"
license = "MPL-2.0"
publish = true

[dependencies]
atoi = "2.0.0"
libc = "0.2.141"
tracing = "0.1.37"
